name: Run Splice Analysis
on:
  workflow_dispatch: 
    inputs:
      splice:
        description: 'Name of YAML splice config in splices (e.g., curl.yaml)'
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    outputs:
      containers: ${{ steps.generate.outputs.containers }}
      package: ${{ steps.setup.outputs.package }}
      splice: ${{ steps.setup.outputs.splice }}
      command: ${{ steps.setup.outputs.command }}
      experiment: ${{ steps.setup.outputs.experiment }}
      replace: ${{ steps.setup.outputs.replace }}

    name: Build Matrix
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup splice
        id: setup
        env:
          package: ${{ github.event.inputs.splice }}
        run: |
            pip install pyaml
            python scripts/prepare-splice.py ${package}
      - name: Generate matrix
        id: generate
        run: |
            pip install requests
            python scripts/generate-matrix.py ${{ steps.setup.outputs.package }} ${{ steps.setup.outputs.splice }} ${{ steps.setup.outputs.replace }} ${{ steps.setup.outputs.experiment }} ${{ steps.setup.outputs.command }}
            
  build:
    runs-on: ubuntu-latest
    needs:
      - prepare
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        # Each entry is a container, and then compiler within it, and a tag for the version, and the version
        # [container, label, container_name, pkg, version, splice, command, experiment, replace]
        container: ${{ fromJson(needs.prepare.outputs.containers) }}
        arch: ['linux/amd64'] # linux/ppc64le,linux/arm64 these take forever

    # Run tests inside the container above - we could also build with Dockerfile if desired
    container:
      image: ${{ matrix.container[0] }}
      options: "--platform=${{ matrix.arch }}"

    name: ${{ matrix.package }} ${{ matrix.container[0] }} ${{ matrix.container[3]}}@${{ matrix.container[4] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Result Name
        env:
          splice_id: pkg-${{ matrix.container[3] }}-${{ matrix.container[4] }}-splice-${{ matrix.container[5] }}-with-${{ matrix.container[8] }}-experiment-${{ matrix.container[7] }}
        run: echo "splice_id=${splice_id}" >> $GITHUB_ENV

      - name: Install system dependencies
        run: apt-get install -y libxm4
      - name: Run analysis
        env:
          SPACK_ADD_DEBUG_FLAGS: true
          splice_id: pkg-${{ matrix.container[3] }}-${{ matrix.container[4] }}-splice-${{ matrix.container[5] }}-with-${{ matrix.container[8] }}-experiment-${{ matrix.container[7] }}
        run: |
          apt-get update && apt-get install -y vim libtool
          cd /opt/spack && git fetch && git checkout vsoch/db-17-splice && cd -
          printf "spack python splice.py splice ${{ matrix.container[3] }}@${{ matrix.container[4] }} ${{ matrix.container[5] }} ${{ matrix.container[8] }} --outfile ${{ env.splice_id }}-splices.json --experiment ${{ matrix.container[7]}} ${{ matrix.container[6] }}\n"
          spack python splice.py splice "${{ matrix.container[3] }}@${{ matrix.container[4] }}" "${{ matrix.container[5] }}" "${{ matrix.container[8] }}" --outfile "${{ env.splice_id }}-splices.json" --experiment "${{ matrix.container[7]}}" "${{ matrix.container[6]}}"

      - name: Save Result Artifact
        uses: actions/upload-artifact@v2
        with:
          name: "test-results-${{ env.splice_id }}"
          path: ./${{ env.splice_id }}-splices.json
